### ISSUE TITLE
package 'oracle-java7-installer' has no installation candidate

### ISSUE THREAD

**Issue by teleivo** [Spantree/puppet-java7#2]
Hello!

on Ubuntu 14.04 64bit with puppet version 3.4.3 and module versions
puppet-apt: 2.1.1
spantree-java7: 0.3.1

I get following error message:

![spantree-java7-error](https://cloud.githubusercontent.com/assets/4661144/10281585/cba9e690-6b75-11e5-9c80-49dd4c6585b6.png)

after I run following init.pp manifest:

```puppet
Exec {
    path => [ '/usr/bin', '/bin', '/usr/sbin', '/sbin' ]
}

package { [ 'unzip', 'curl', 'python-software-properties', 'software-properties-common' ]: }

class { 'java7':
  require => [ Package['python-software-properties'],
  Package['software-properties-common'] ]
}
```

The problem is that the 'apt-get update' which should be triggered by the following in apt/ppa.pp
https://github.com/puppetlabs/puppetlabs-apt/blob/2.1.x/manifests/ppa.pp#L48
```puppet
    exec { "add-apt-repository-${name}":
      environment => $_proxy_env,
      command     => "/usr/bin/add-apt-repository ${options} ${name}",
      unless      => "/usr/bin/test -s ${::apt::sources_list_d}/${sources_list_d_filename}",
      user        => 'root',
      logoutput   => 'on_failure',
      notify      => Class['apt::update'],
      require     => $_require,
    }
```

is called after Package['oracle-java7-installer'].

So when I apply the init.pp twice it works, but never the first time on a fresh vm.

Have you experienced anything similar? Any hints on how to solve this?

Thanks a lot!

**Comment by feniix** [comment]
Sorry for the delay, I am releasing a new version of the module that fixes this issue.

**Comment by feniix** [comment]
It should be fixed now
