### ISSUE TITLE
apt-update executes on every puppet run

### ISSUE THREAD

**Issue by Conzar** [Spantree/puppet-java7#3]
On every puppet run, puppet reports the following:
`/Stage[main]/Java7/Exec[apt-update]/returns: executed successfully`

The problem is with: https://github.com/Spantree/puppet-java7/blob/master/manifests/init.pp#L54

It should be something like this
`exec { 'apt-update':
        command => '/usr/bin/apt-get update',
        refreshonly => true,
        subscribe => [
          Apt::Ppa['ppa:webupd8team/java']
        ],
      }`

**Comment by feniix** [comment]
completed
